class Text:
    NORMAL = "\x0f"
    COLOR = "\x03"
    HEX_COLOR = "\x04"
    BOLD = "\x02"
    ITALIC = "\x1d"
    UNDERLINE = "\x1f"
    STRIKETHROUGH = "\x1e"
    MONOSPACE = "\x11"
    REVERSE = "\x16"


class Color:
    WHITE = "00"
    BLACK = "01"
    BLUE = "02"
    GREEN = "03"
    RED = "04"
    BROWN = "05"
    PURPLE = "06"
    ORANGE = "07"
    YELLOW = "08"
    LIGHT_GREEN = "09"
    TEAL = "10"
    LIGHT_CYAN = "11"
    LIGHT_BLUE = "12"
    PINK = "13"
    GREY = "14"
    LIGHT_GREY = "15"
